"""empty message

Revision ID: fa2055ef16c0
Revises: 9ea4bb51760e
Create Date: 2023-11-01 09:15:02.488908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2055ef16c0'
down_revision = '9ea4bb51760e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description',
    sa.Column('des_id', sa.Integer(), nullable=False),
    sa.Column('des', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('des_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description')
    # ### end Alembic commands ###
